### ISSUE TITLE
how use ``` OH_NativeWindow_CreateNativeWindow ```

### ISSUE THREAD

**Issue by songhuaixu** [openharmony-rs/ohos-sys#41]
`
int32_t OH_NativeWindow_CreateNativeWindowFromSurfaceId (uint64_t surfaceId, OHNativeWindow **window)
`

How to convert uint64_t to * mut c_oid

**Comment by jschwe** [comment]
Please consult the OpenHarmony documentation: https://docs.openharmony.cn/pages/v5.0/zh-cn/application-dev/reference/apis-arkgraphics2d/external__window_8h.md

I myself have no idea, since the documentation doesn't seem to mention what a `surfaceId` is supposed to be. I'm hoping that future updates of the OH SDK will improve the documentation, because right now it is quite lacking.

**Comment by songhuaixu** [comment]
Oh, I see. `OH_NativeWindow_CreateNativeWindowFromSurfaceId ` and `OH_NativeWindow_CreateNativeWindow ` are two APIs
